title: <p align="center"> Masood Pasha </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/DS-MAS">GitHub</a>
  
  <br>   
  I'm working in BI/Analytics area and in parallel i am currently pursuing Masters in Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Aiming to boost my experinace by studying and mastering real Data science skills 
  <br>
  </p>



theme: jekyll-theme-minimal
